src/Entity/Metas.php
<?php

namespace App\Entity;

use App\Repository\MetasRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=MetasRepository::class)
 */
class Metas
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Post::class, inversedBy="metas")
     * @ORM\JoinColumn(nullable=false)
     */
    private $post;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $meta_key;

    /**
     * @ORM\Column(type="string", length=1000)
     */
    private $value;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPost(): ?Post
    {
        return $this->post;
    }

    public function setPost(?Post $post): self
    {
        $this->post = $post;

        return $this;
    }

    public function getMetaKey(): ?string
    {
        return $this->meta_key;
    }

    public function setMetaKey(string $meta_key): self
    {
        $this->meta_key = $meta_key;

        return $this;
    }

    public function getValue(): ?string
    {
        return $this->value;
    }

    public function setValue(string $value): self
    {
        $this->value = $value;

        return $this;
    }
}

src/Entity/Post.php
<?php

namespace App\Entity;

use App\Repository\PostRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PostRepository::class)
 */
class Post
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $status;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    /**
     * @ORM\OneToMany(targetEntity=Metas::class, mappedBy="post")
     */
    private $metas;

    public function __construct()
    {
        $this->metas = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * @return Collection|Metas[]
     */
    public function getMetas(): Collection
    {
        return $this->metas;
    }

    public function addMeta(Metas $meta): self
    {
        if (!$this->metas->contains($meta)) {
            $this->metas[] = $meta;
            $meta->setPost($this);
        }

        return $this;
    }

    public function removeMeta(Metas $meta): self
    {
        if ($this->metas->removeElement($meta)) {
            if ($meta->getPost() === $this) {
                $meta->setPost(null);
            }
        }

        return $this;
    }
}

src/Form/PostType.php
<?php

namespace App\Form;

use App\Entity\Post;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PostType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', TextType::class)
            ->add('content', TextareaType::class, array(
                'attr' => array(
                    'class' => 'summernote'
                )
            ));
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Post::class,
        ]);
    }
}

src/Controller/Post/PostCreateController.php
<?php


namespace App\Controller\Post;


use App\Controller\BaseController;
use App\Entity\Post;
use App\Form\PostType;
use DateTime;
use Exception;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class PostCreateController extends BaseController
{
    // Form create page
    /**
     * @Route("/post/create", name="post_create", methods={"GET"})
     */
    public function postCreate(){
        $forRender = parent::renderDefault();
        $forRender["title"] = "Post Create";

        $form = $this->createForm(PostType::class);

        $forRender["form"] = $form->createView();

        return $this->render("post/postcreate.html.twig", $forRender);
    }


    // Form create POST request
    /**
     * @Route("/post/create", name="post_create_request", methods={"POST"})
     * @param Request $request
     * @return Response
     * @throws Exception
     */
    public function postCreatePost(Request $request){

        $post = new Post();

        $em = $this->getDoctrine()->getManager();

        $form = $this->createForm(PostType::class, $post);
        $form->handleRequest($request);

        $status = "error";

        // Checking for form submit
        if ( $form->isSubmitted() && $form->isValid() ){

            $post->setStatus("Published");
            $post->setCreatedAt(new DateTime('now'));

            $em->persist($post);
            try {
                // Adding new post to database
                $em->flush();
                $status = "success";
            } catch (\Exception $e) {}

        }else{
            $status = "error";
        }

        // Sending data to ajax function
        return new JsonResponse($status);

    }

}

src/Controller/Post/PostListController.php
<?php


namespace App\Controller\Post;


use App\Controller\BaseController;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class PostListController extends BaseController
{

    // Posts list page
    /**
     * @Route("/post/postlist", name="post_list")
     * @param PaginatorInterface $paginator
     * @param Request $request
     * @return Response
     */
    public function postList(PaginatorInterface $paginator, Request $request){
        $forRender = parent::renderDefault();
        $forRender["title"] = "Post list";

        $em = $this->getDoctrine()->getManager();


        // Getting all posts ordered by date
        $query = $em->getRepository('App:Post')
            ->createQueryBuilder('p')
            ->orderBy('p.created_at', 'DESC')
            ->getQuery()
            ->getResult();


        // Creating pagination
        $pagination = $paginator->paginate(
            $query,
            $request->query->getInt('page', 1),
            5
        );

        $forRender["pagination"] = $pagination;

        return $this->render("post/postlist.html.twig", $forRender);
    }

}

src/Controller/Post/PostMetaUpdate.php
<?php


namespace App\Controller\Post;


use App\Controller\BaseController;
use App\Entity\Metas;
use App\Form\MetasType;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class PostMetaUpdate extends BaseController
{

    // Meta create page
    /**
     * @Route("/post/postmeta/{id}", name="meta_update", methods={"GET"})
     * @param int $id
     * @return Response
     */
    public function postUpdate(int $id){

        $meta = new Metas();

        $forRender = parent::renderDefault();
        $forRender["title"] = "Meta Update";

        $em = $this->getDoctrine()->getManager();

        $meta = $em->getRepository('App:Metas')->find($id);

        $form = $this->createForm(MetasType::class, $meta);

        $forRender["meta"] = $meta;
        $forRender["form"] = $form->createView();

        return $this->render("post/postmetaupdate.html.twig", $forRender);
    }


    // Meta create POST request
    /**
     * @Route("/post/postmeta/{id}", name="meta_update_request", methods={"POST"})
     * @param Metas $meta
     * @param Request $request
     * @return Response
     * @throws \Exception
     */
    public function postUpdateRequest(Metas $meta, Request $request){

        $status = "error";

        $em = $this->getDoctrine()->getManager();

        $form = $this->createForm(MetasType::class, $meta);
        $form->handleRequest($request);

        if ($form->isSubmitted()){

            $meta = $form->getData();

            $em->persist($meta);

            try {
                // Updating meta
                $em->flush();
                $status = "success";
            }catch (\Exception $e){
                $status = $e;
            }

        }else{
            $status = "error";
        }

        // Sending data to ajax function
        return new JsonResponse($status);

    }
}

src/Controller/Post/PostUpdateController.php
<?php


namespace App\Controller\Post;


use App\Controller\BaseController;
use App\Entity\Post;
use App\Form\MetasType;
use App\Form\PostType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class PostUpdateController extends BaseController
{


    // Post update page
    /**
     * @Route("/post/postupdate/{id}", name="post_update", methods={"GET"})
     * @param int $id
     * @return Response
     */
    public function postUpdate(int $id){

        $post = new Post();

        $forRender = parent::renderDefault();
        $forRender["title"] = "Post Update";

        $em = $this->getDoctrine()->getManager();

        $post = $em->getRepository('App:Post')->find($id);

        $form = $this->createForm(PostType::class, $post);

        $forRender["post"] = $post;
        $forRender["form"] = $form->createView();

        return $this->render("post/postupdate.html.twig", $forRender);
    }


    // Post update POST request
    /**
     * @Route("/post/postupdate/{id}", name="post_update_request", methods={"POST"})
     * @param Post $post
     * @param Request $request
     * @return Response
     * @throws \Exception
     */
    public function postUpdateRequest(Post $post, Request $request){

        $status = "error";

        $em = $this->getDoctrine()->getManager();

        $form = $this->createForm(PostType::class, $post);
        $form->handleRequest($request);

        if ($form->isSubmitted()){

            $post = $form->getData();
            $post->setUpdatedAt(new \DateTime("now"));

            $em->persist($post);

            try {
                // Updating post
                $em->flush();
                $status = "success";
            }catch (\Exception $e){
                $status = $e;
            }

        }else{
            $status = "error";
        }

        // Sending data to ajax function
        return new JsonResponse($status);

    }

}

src/Controller/Post/PostViewController.php
<?php


namespace App\Controller\Post;


use App\Controller\BaseController;
use App\Entity\Metas;
use App\Form\MetasType;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class PostViewController extends BaseController
{

    // Getting data about current post
    /**
     * @Route("/post/postview/{id}", name="post_view", methods={"GET"})
     * @param int $id
     * @return Response
     */
    public function postView(int $id){

        $form = $this->createForm(MetasType::class);


        $forRender = parent::renderDefault();
        $forRender["title"] = "Post View";

        $em = $this->getDoctrine()->getManager();


        $post = $em->getRepository('App:Post')->find($id);
        $metas = $em->getRepository('App:Metas')->findBy(["post"=>$post->getId()]);

        $forRender["post"] = $post;
        $forRender["form"] = $form->createView();
        $forRender["metas"] = $metas;


        return $this->render("post/postview.html.twig", $forRender);
    }

    // Create meta form
    /**
     * @Route("/post/postview/createmeta/{id}", name="post_view_request", methods={"POST"})
     * @param Request $request
     * @param int $id
     * @return Response
     */
    public function postViewPost(Request $request, int $id){

        $meta = new Metas();

        $em = $this->getDoctrine()->getManager();

        $form = $this->createForm(MetasType::class, $meta);
        $form->handleRequest($request);

        $status = "error";

        if ( $form->isSubmitted() && $form->isValid() ){

            $post = $em->getRepository('App:Post')->find($id);
            $meta->setPost($post);

            $em->persist($meta);

            try {
                // Adding new meta to database
                $em->flush();
                $status = "success";
            } catch (\Exception $e) {}

        }else{
            $status = "error";
        }

        // Sending data to ajax function
        return new JsonResponse($status);

    }

}

templates/post/postcreate.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ title }}{% endblock %}

{% block body %}

    {% include 'menu.html.twig' %}



    <div class="container-fluid d-flex justify-content-center">
        <div class="col-12 col-lg-6 col-md-6 p-3 shadow mt-5 rounded-2">
            <h1 class="h3 mb-3 font-weight-normal text-uppercase">Post create</h1>

            {{ form_start(form, {'method': 'POST' , 'attr': {'id': 'form', 'onsubmit': 'return false;'}}) }}
                {{ form_label(form.title, null, {
                    'label': 'Post title:',
                    'label_attr': {'class': 'form-label'}
                }) }}
            {{ form_widget(form.title, {'attr': {'class': 'form-control'}} ) }}

            {{ form_start(form) }}
            {{ form_label(form.content, null, {
                'label': 'Post content:',
                'label_attr': {'class': 'form-label'}
            }) }}
            {{ form_widget(form.content, {'attr': {'class': 'form-control summernote'}} ) }}

            <button id="formsubmit" type="submit" class="btn btn-block w-100 mt-3 btn-primary">
                Save
            </button>
            {{ form_end(form) }}

        </div>
    </div>
    <div class="bg-success text-white toast d-flex align-items-center position-absolute top-50 start-0" role="alert" aria-live="assertive" aria-atomic="true">
        <div class="toast-body">
            Hello, world! This is a toast message.
        </div>
        <button type="button" class="btn-close ms-auto me-2" data-bs-dismiss="toast" aria-label="Close"></button>
    </div>


{% endblock %}

{% block js %}
    <script>
        summernoteInit();

        $(document).on("click", "#formsubmit", function(e) {
            e.preventDefault();
            ajaxRequest("/post/create", $("#form"));
        });
    </script>

{% endblock %}

templates/post/postlist.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ title }}{% endblock %}

{% block body %}

    {% include 'menu.html.twig' %}

    <div class="container-fluid d-flex justify-content-center">
        <div class="col-12 col-md-6 col-lg-6 w-75 mt-3">
            <div class="list-group">
                {% for post in pagination %}
                    {% set content = post.content|length > 350 ? post.content|slice(0, 350) ~ '...' : post.content %}

                        <a href="/post/postview/{{ post.id }}" class="list-group-item list-group-item-action" aria-current="true">

                            <div class="d-flex w-100 justify-content-between">
                                <h5 class="mb-1">{{ post.title }}</h5>
                                <small>{{ post.createdat|date("m.d.Y") }}</small>
                            </div>
                            <div>
                                <p class="mb-1">{{ content|striptags }}</p>
                            </div>
                            <div>
                                {% if post.metas %}
                                    {% for meta in  post.metas  %}
                                        <small class="badge bg-primary rounded-pill">
                                            {{ meta.metaKey }} : {{ meta.value }}
                                        </small>
                                    {% endfor %}
                                {%  endif %}
                            </div>
                        </a>

                {% endfor %}
            </div>

            <div class="navigation d-flex justify-content-center mt-3">
                {{ knp_pagination_render(pagination) }}
            </div>
        </div>
    </div>
{% endblock %}

templates/post/postmetaupdate.html.twig
{% extends 'base.html.twig' %}


{% block title %} {{ title }} {% endblock %}
{% block body %}

    {% include 'menu.html.twig' %}


    <div class="container-fluid d-flex justify-content-center">
        <div class="col-12 col-lg-6 col-md-6 p-3 shadow mt-5 rounded-2">
            <h1 class="h3 mb-3 font-weight-normal text-uppercase">Meta update</h1>

            {{ form_start(form, {'method': 'POST' , 'attr': {'id': 'form', 'onsubmit': 'return false;'}}) }}
                {{ form_label(form.meta_key, null, {
                    'label': 'Meta key:',
                    'label_attr': {'class': 'form-label'}
                }) }}
                {{ form_widget(form.meta_key, {'attr': {'class': 'form-control'}} ) }}

                {{ form_start(form) }}
                {{ form_label(form.value, null, {
                    'label': 'Meta value:',
                    'label_attr': {'class': 'form-label'}
                }) }}
                {{ form_widget(form.value, {'attr': {'class': 'form-control'}} ) }}

                <button id="formsubmit" type="submit" class="btn btn-block w-100 mt-3 btn-primary">
                    Save
                </button>
            {{ form_end(form) }}

        </div>
    </div>
    <div class="bg-success text-white toast d-flex align-items-center position-absolute top-50 start-0" role="alert" aria-live="assertive" aria-atomic="true">
        <div class="toast-body"></div>
        <button type="button" class="btn-close ms-auto me-2" data-bs-dismiss="toast" aria-label="Close"></button>
    </div>
{% endblock %}

{% block js %}
    <script>
        $(document).on("click", "#formsubmit", function(e){
            e.preventDefault();
            ajaxRequest("/post/postmeta/{{ meta.id }}", $('#form'));
        });
    </script>
{% endblock %}

templates/post/postupdate.html.twig
{% extends 'base.html.twig' %}


{% block title %} {{ title }} {% endblock %}
{% block body %}

    {% include 'menu.html.twig' %}




    <div class="container-fluid d-flex justify-content-center">
        <div class="col-12 col-lg-6 col-md-6 p-3 shadow mt-5 rounded-2">
            <h1 class="h3 mb-3 font-weight-normal text-uppercase">Post update</h1>

            {{ form_start(form, {'method': 'POST' , 'attr': {'id': 'form', 'onsubmit': 'return false;'}}) }}
            {{ form_label(form.title, null, {
                'label': 'Post title:',
                'label_attr': {'class': 'form-label'}
            }) }}
            {{ form_widget(form.title, {'attr': {'class': 'form-control'}} ) }}

            {{ form_start(form) }}
            {{ form_label(form.content, null, {
                'label': 'Post content:',
                'label_attr': {'class': 'form-label'}
            }) }}
            {{ form_widget(form.content, {'attr': {'class': 'form-control summernote'}} ) }}

            <button id="formsubmit" type="submit" class="btn btn-block w-100 mt-3 btn-primary">
                Save
            </button>
            {{ form_end(form) }}

        </div>
    </div>
    <div class="bg-success text-white toast d-flex align-items-center position-absolute top-50 start-0" role="alert" aria-live="assertive" aria-atomic="true">
        <div class="toast-body">
            Hello, world! This is a toast message.
        </div>
        <button type="button" class="btn-close ms-auto me-2" data-bs-dismiss="toast" aria-label="Close"></button>
    </div>
{% endblock %}


{% block js %}
    <script>
        summernoteInit();

        $(document).on("click", "#formsubmit", function(e){
            e.preventDefault();
            ajaxRequest("/post/postupdate/{{ post.id }}", $('#form'));
        });

    </script>
{% endblock %}

templates/post/postview.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ title }}{% endblock %}

{% block body %}

    {% include 'menu.html.twig' %}

    <div class="container-fluid d-flex justify-content-center">
        <div class="col-12 col-md-6 col-lg-8 mt-2">
            <h1 class="border-start border-primary border-5 p-3 text-uppercase">{{ post.title }}</h1>

            {% if post.updatedAt %}

                <h6 class="border-start border-dark border-5 ps-3" role="alert">
                    Updated {{ post.updatedAt|date("m.d.Y.h \\a\\t H:i:s") }}
                </h6>

            {% endif %}

            {% for meta in metas %}

                <h6 class="border-start border-dark border-5 ps-3"><a href="{{ path('meta_update', {'id': meta.id}) }}">{{ meta.metaKey }}: {{ meta.value }}</a></h6>

            {% endfor %}


            <div>
                {{ post.content|raw }}
            </div>

        </div>
    </div>


    <div class="d-flex flex-column position-fixed bottom-0 end-0 me-5 mb-5">
        <button type="button" id="myInput" class="btn btn-primary text-white text-uppercase mb-2" data-bs-toggle="modal" data-bs-target="#myModal">
            <i class="fas fa-plus-circle"></i>
        </button>
        <a href="/post/postupdate/{{ post.id }}" class="btn btn-primary text-white text-uppercase" data-bs-toggle="modal">
            <i class="fas fa-edit"></i>
        </a>
    </div>

    <div class="modal fade" id="myModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">

                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Add meta</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    {{ form_start(form, {'method': 'POST' , 'attr': {'id': 'form', 'onsubmit': 'return false;'}}) }}
                    {{ form_label(form.meta_key, null, {
                        'label': 'Meta key:',
                        'label_attr': {'class': 'form-label'}
                    }) }}
                    {{ form_widget(form.meta_key, {'attr': {'class': 'form-control'}} ) }}

                    {{ form_start(form) }}
                    {{ form_label(form.value, null, {
                        'label': 'Meta value:',
                        'label_attr': {'class': 'form-label'}
                    }) }}
                    {{ form_widget(form.value, {'attr': {'class': 'form-control'}} ) }}

                    <button id="formsubmit" type="submit" class="btn btn-block w-100 mt-3 btn-primary">
                        Save
                    </button>
                    {{ form_end(form) }}
                </div>
            </div>
        </div>
    </div>
    <div class="bg-success text-white toast d-flex align-items-center position-fixed top-50 start-0" role="alert" aria-live="assertive" aria-atomic="true">
        <div class="toast-body">
            Hello, world! This is a toast message.
        </div>
        <button type="button" class="btn-close ms-auto me-2" data-bs-dismiss="toast" aria-label="Close"></button>
    </div>

{% endblock %}

{% block js %}

    <script>
        var myModal = document.getElementById('myModal');
        var myInput = document.getElementById('myInput');

        myModal.addEventListener('shown.bs.modal', function () {
            myInput.focus()
        });

        $(document).on("click", "#formsubmit", function(e){
            e.preventDefault();
            ajaxRequest("/post/postview/createmeta/{{ post.id }}", $("#form"));
        });
    </script>

{% endblock %}